"""empty message

Revision ID: fcf75fdfd8fc
Revises: 1d2480ac3adb
Create Date: 2018-08-25 18:46:35.264319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf75fdfd8fc'
down_revision = '1d2480ac3adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('friended_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'friends', 'user', ['friended_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_column('friends', 'friended_id')
    # ### end Alembic commands ###
